using System;
using ObjCRuntime;
using Foundation;

namespace Net.Agora.Signaling.Mac {

	// Hand-written against the real AgoraRtmKit.xcframework headers from AgoraRtm_macOS (AgoraRtm_Apple SwiftPM binary) 2.2.6
	// (io.agora:agora-rtm's iOS counterpart) rather than generated by Objective Sharpie — same
	// reasoning as the RTC bindings' ApiDefinition.cs: sharpie's bundled clang cannot parse SDKs
	// from current Xcode.
	//
	// Scoped to what the thin Net.Agora.Signaling client needs — construct the client, log in and
	// out, subscribe/unsubscribe message channels, publish string messages, renew the token, and
	// the delegate callbacks for those — not the SDK's full surface (stream channels and topics,
	// presence, storage, locks, history). Extend here as more of AgoraRtmClientKit.h is needed.
	// Enums live in StructsAndEnums.cs; the block delegate type stays here — the binding generator
	// emits a trampoline for a delegate declared in the api definition file itself, and duplicates
	// it if the same type is declared again in the core source file.

	// AgoraRtmOperationBlock — AgoraRtmObjects.h. Exactly one of the two parameters is nil: a
	// response on success, an error on failure.
	public delegate void AgoraRtmOperationHandler ([NullAllowed] AgoraRtmCommonResponse response, [NullAllowed] AgoraRtmErrorInfo errorInfo);

	// AgoraRtmCommonResponse — AgoraRtmObjects.h. Bound as an opaque type: it is only used here as
	// the success half of the completion blocks. Add properties as callers need them.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtmCommonResponse {
	}

	// AgoraRtmErrorInfo — AgoraRtmObjects.h. An NSError subclass: Code/Domain/LocalizedDescription
	// come from the base, the RTM-specific triple is bound here. ErrorCode is the SDK's
	// AgoraRtmErrorCode — ~100 values; carried as its raw NSInteger rather than binding an enum
	// consumers would mostly pass to GetErrorReason anyway.
	[BaseType (typeof (NSError))]
	public interface AgoraRtmErrorInfo {
		[Export ("errorCode")]
		nint ErrorCode { get; set; }

		[Export ("operation")]
		string Operation { get; set; }

		[Export ("reason")]
		string Reason { get; set; }
	}

	// AgoraRtmClientConfig — AgoraRtmObjects.h. Only the constructor every client needs; the
	// advanced knobs (area code, proxy, encryption, log config) stay unbound until needed.
	[BaseType (typeof (NSObject))]
	[DisableDefaultCtor]
	public interface AgoraRtmClientConfig {
		[Export ("initWithAppId:userId:")]
		NativeHandle Constructor (string appId, string userId);

		[Export ("appId", ArgumentSemantic.Copy)]
		string AppId { get; set; }

		[Export ("userId", ArgumentSemantic.Copy)]
		string UserId { get; set; }
	}

	// AgoraRtmMessage — AgoraRtmObjects.h. Exactly one of the two properties is non-nil.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtmMessage {
		[Export ("rawData", ArgumentSemantic.Copy)]
		[NullAllowed]
		NSData RawData { get; set; }

		[Export ("stringData", ArgumentSemantic.Copy)]
		[NullAllowed]
		string StringData { get; set; }
	}

	// AgoraRtmMessageEvent — AgoraRtmObjects.h.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtmMessageEvent {
		[Export ("channelType")]
		AgoraRtmChannelType ChannelType { get; set; }

		[Export ("channelName", ArgumentSemantic.Copy)]
		string ChannelName { get; set; }

		[Export ("message", ArgumentSemantic.Copy)]
		AgoraRtmMessage Message { get; set; }

		[Export ("publisher", ArgumentSemantic.Copy)]
		string Publisher { get; set; }

		[Export ("customType", ArgumentSemantic.Copy)]
		[NullAllowed]
		string CustomType { get; set; }

		[Export ("timestamp")]
		ulong Timestamp { get; set; }
	}

	// AgoraRtmPublishOptions / AgoraRtmSubscribeOptions — AgoraRtmObjects.h. Bound opaque: the
	// client methods accept nil for both, which is all the thin client uses; the types exist so
	// the signatures match the headers.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtmPublishOptions {
	}

	[BaseType (typeof (NSObject))]
	public interface AgoraRtmSubscribeOptions {
	}

	[BaseType (typeof (NSObject))]
	[DisableDefaultCtor]
	public interface AgoraRtmClientKit {

		// - (instancetype)initWithConfig:delegate:error: — returns nil (with the error populated)
		// for an invalid config, e.g. an empty App ID.
		[Export ("initWithConfig:delegate:error:")]
		NativeHandle Constructor (AgoraRtmClientConfig config, [NullAllowed] AgoraRtmClientDelegate del, out NSError error);

		// The completion methods carry [Async] so every operation also has an awaitable form:
		// LoginAsync and friends return Task<AgoraRtmOperationResult> (a generated class holding
		// the Response/ErrorInfo pair). The Task completes rather than faults on an RTM error —
		// deliberately, because the SDK answers some successes with a non-nil errorInfo whose
		// errorCode is 0 (Ok), so "errorInfo present" is not "failed"; callers check
		// result.ErrorInfo?.ErrorCode. The callback overloads remain for consumers who want them.

		// - (void)loginByToken:completion: — the token doubles as the App ID in projects with
		// App ID-only authentication.
		[Export ("loginByToken:completion:")]
		[Async (ResultTypeName = "AgoraRtmOperationResult")]
		void Login ([NullAllowed] string token, [NullAllowed] AgoraRtmOperationHandler completion);

		[Export ("logout:")]
		[Async (ResultTypeName = "AgoraRtmOperationResult")]
		void Logout ([NullAllowed] AgoraRtmOperationHandler completion);

		[Export ("renewToken:completion:")]
		[Async (ResultTypeName = "AgoraRtmOperationResult")]
		void RenewToken (string token, [NullAllowed] AgoraRtmOperationHandler completion);

		[Export ("subscribeWithChannel:option:completion:")]
		[Async (ResultTypeName = "AgoraRtmOperationResult")]
		void Subscribe (string channelName, [NullAllowed] AgoraRtmSubscribeOptions option, [NullAllowed] AgoraRtmOperationHandler completion);

		[Export ("unsubscribeWithChannel:completion:")]
		[Async (ResultTypeName = "AgoraRtmOperationResult")]
		void Unsubscribe (string channelName, [NullAllowed] AgoraRtmOperationHandler completion);

		// - (void)publish:message:option:completion: — the string-payload overload; raw NSData has
		// its own selector, unbound until the client needs it.
		[Export ("publish:message:option:completion:")]
		[Async (ResultTypeName = "AgoraRtmOperationResult")]
		void Publish (string channelName, string message, [NullAllowed] AgoraRtmPublishOptions option, [NullAllowed] AgoraRtmOperationHandler completion);

		// - (void)addDelegate: / removeDelegate: — RTM supports any number of listeners besides
		// the one passed to the constructor. Bound so a consumer can attach a listener without
		// owning client construction (the constructor-injected delegate remains for the common
		// case). The kit holds these weakly: the caller must keep its listener referenced, same
		// as the constructor delegate.
		[Export ("addDelegate:")]
		void AddDelegate (AgoraRtmClientDelegate del);

		[Export ("removeDelegate:")]
		void RemoveDelegate (AgoraRtmClientDelegate del);

		// - (AgoraRtmErrorCode)destroy — synchronous teardown; the client is unusable afterwards.
		[Export ("destroy")]
		nint Destroy ();

		[Static]
		[Export ("getVersion")]
		string GetVersion ();

		// + (NSString *)getErrorReason: — the parameter is AgoraRtmErrorCode, carried raw for the
		// same reason as AgoraRtmErrorInfo.ErrorCode.
		[Static]
		[Export ("getErrorReason:")]
		[return: NullAllowed]
		string GetErrorReason (nint errorCode);
	}

	// AgoraRtmClientDelegate — AgoraRtmClientKit.h. Every method is @optional; scoped here to the
	// callbacks the thin client turns into C# events.
	[Protocol]
	[Model]
	[BaseType (typeof (NSObject))]
	public interface AgoraRtmClientDelegate {

		[Export ("rtmKit:didReceiveMessageEvent:")]
		void DidReceiveMessageEvent (AgoraRtmClientKit rtmKit, AgoraRtmMessageEvent @event);

		// - (void)rtmKit:channel:connectionChangedToState:reason: — the reason parameter is
		// AgoraRtmClientConnectionChangeReason, ~30 values; carried raw.
		[Export ("rtmKit:channel:connectionChangedToState:reason:")]
		void ConnectionChangedToState (AgoraRtmClientKit rtmKit, string channelName, AgoraRtmClientConnectionState state, nint reason);

		[Export ("rtmKit:tokenPrivilegeWillExpire:")]
		void TokenPrivilegeWillExpire (AgoraRtmClientKit rtmKit, [NullAllowed] string channel);
	}
}
