using System;
using ObjCRuntime;
using Foundation;
using AppKit;

namespace Net.Agora.Video.Mac {

	// Hand-written against the real AgoraRtcKit.xcframework headers (Agora Video macOS SDK 4.6.2,
	// AgoraRtcEngine_macOS) rather than generated by Objective Sharpie: sharpie's bundled clang
	// predates Xcode 15's module-map format and cannot parse any recent SDK
	// (`module '_c_standard_library_obsolete' requires feature
	// 'found_incompatible_headers__check_search_paths'`) — a known, unresolved incompatibility, not
	// something fixable from this repository. See build/fetch-video.sh.
	//
	// The macOS AgoraRtcEngineKit surface is materially the same Objective-C API as iOS; this file
	// is the iOS binding ported, with one type change that AgoraObjects.h itself makes: VIEW_CLASS
	// is UIView on iOS and NSView on macOS, so AgoraRtcVideoCanvas.view is an NSView here.
	//
	// Scoped to what the thin Net.Agora.Video client needs — create the engine, join/leave a
	// channel, publish/mute audio and video, render local/remote video, and the delegate callbacks
	// for those — not the SDK's full surface (media player, spatial audio, screen sharing, the macOS
	// audio/video device-selection API, ...). Extend here as more of AgoraRtcEngineKit.h is needed.
	// Enums live in StructsAndEnums.cs; the block delegate types stay here — the binding generator
	// emits a trampoline for a delegate declared in the api definition file itself, and duplicates
	// it if the same type is declared again in the core source file.

	// Objective-C blocks used as completion handlers on AgoraRtcEngineKit (AgoraRtcEngineKit.h).
	public delegate void AgoraJoinChannelSuccessHandler (string channel, nuint uid, nint elapsed);
	public delegate void AgoraLeaveChannelHandler (AgoraChannelStats stats);

	// AgoraChannelStats — AgoraObjects.h. Bound as an opaque type: it is only used here as the
	// LeaveChannel completion handler's parameter type. Add properties as callers need the stats.
	[BaseType (typeof (NSObject))]
	public interface AgoraChannelStats {
	}

	// AgoraRtcEngineConfig — AgoraObjects.h. Only the two properties every engine needs.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtcEngineConfig {
		[Export ("appId", ArgumentSemantic.Copy)]
		[NullAllowed]
		string AppId { get; set; }

		[Export ("channelProfile")]
		AgoraChannelProfile ChannelProfile { get; set; }
	}

	// AgoraRtcVideoCanvas — AgoraObjects.h. VIEW_CLASS is NSView on macOS (UIView on iOS), so the
	// SDK renders into whatever NSView is set here.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtcVideoCanvas {
		[Export ("uid")]
		nuint Uid { get; set; }

		[Export ("view", ArgumentSemantic.Strong)]
		[NullAllowed]
		NSView View { get; set; }
	}

	// AgoraRtcAudioVolumeInfo — AgoraObjects.h. One speaker's entry in the volume indication
	// callback: uid 0 is the local user in the local callback, volume ranges 0–255.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtcAudioVolumeInfo {
		[Export ("uid")]
		nuint Uid { get; set; }

		[Export ("volume")]
		nuint Volume { get; set; }
	}

	// Delegates/Events: the generator turns every AgoraRtcEngineDelegate callback into a C# event
	// on the engine (engine.DidJoinChannel += …), backed by an internal delegate it installs via
	// the `delegate` property the first time an event is subscribed. One caveat inherited from
	// how Apple bindings do this everywhere: events and a hand-assigned Delegate are mutually
	// exclusive — subscribing an event replaces whatever delegate was set (including the one
	// passed to SharedEngine), and assigning Delegate afterwards silently detaches the events.
	// Pick one style per engine instance.
	[BaseType (typeof (NSObject), Delegates = new [] { "WeakDelegate" }, Events = new [] { typeof (AgoraRtcEngineDelegate) })]
	[DisableDefaultCtor] // The engine only exists through SharedEngine — `new AgoraRtcEngineKit()`
	                     // compiled before this and handed back a broken non-shared instance.
	public interface AgoraRtcEngineKit {

		// + (instancetype)sharedEngineWithConfig:delegate:
		[Static]
		[Export ("sharedEngineWithConfig:delegate:")]
		AgoraRtcEngineKit SharedEngine (AgoraRtcEngineConfig config, [NullAllowed] AgoraRtcEngineDelegate del);

		// + (void)destroy — call after releasing every reference to the shared instance.
		[Static]
		[Export ("destroy")]
		void Destroy ();

		// @property(nonatomic, weak) id<AgoraRtcEngineDelegate> delegate — the property behind
		// SharedEngine's second argument. The shared AgoraRtcEngineKit.h declares it on macOS too
		// and — unlike the iOS-only selectors called out below — the macOS engine implements it.
		// Weak: the engine does not root the delegate, so keep a reference alive on the caller's
		// side or the callbacks stop with no error.
		[Export ("delegate", ArgumentSemantic.Weak)]
		[NullAllowed]
		NSObject WeakDelegate { get; set; }

		[Wrap ("WeakDelegate")]
		[NullAllowed]
		AgoraRtcEngineDelegate Delegate { get; set; }

		// - (int)joinChannelByToken:channelId:info:uid:joinSuccess:
		[Export ("joinChannelByToken:channelId:info:uid:joinSuccess:")]
		nint JoinChannel ([NullAllowed] string token, string channelId, [NullAllowed] string info, nuint uid, [NullAllowed] AgoraJoinChannelSuccessHandler joinSuccess);

		// - (int)leaveChannel:(void(^)(AgoraChannelStats*))
		[Export ("leaveChannel:")]
		nint LeaveChannel ([NullAllowed] AgoraLeaveChannelHandler leaveChannelBlock);

		[Export ("setChannelProfile:")]
		nint SetChannelProfile (AgoraChannelProfile profile);

		[Export ("setClientRole:")]
		nint SetClientRole (AgoraClientRole role);

		[Export ("enableAudio")]
		nint EnableAudio ();

		[Export ("disableAudio")]
		nint DisableAudio ();

		[Export ("enableVideo")]
		nint EnableVideo ();

		[Export ("disableVideo")]
		nint DisableVideo ();

		[Export ("muteLocalAudioStream:")]
		nint MuteLocalAudioStream (bool mute);

		[Export ("muteLocalVideoStream:")]
		nint MuteLocalVideoStream (bool mute);

		[Export ("setupLocalVideo:")]
		nint SetupLocalVideo ([NullAllowed] AgoraRtcVideoCanvas local);

		[Export ("setupRemoteVideo:")]
		nint SetupRemoteVideo (AgoraRtcVideoCanvas remote);

		[Export ("startPreview")]
		nint StartPreview ();

		[Export ("stopPreview")]
		nint StopPreview ();

		// Deliberately NOT bound on macOS: -switchCamera, -setEnableSpeakerphone: and
		// -setDefaultAudioRouteToSpeakerphone:. The shared AgoraRtcEngineKit.h declares all three,
		// but they are iOS-only — the macOS engine does not implement them, and sending any of them
		// raises "unrecognized selector" (verified on the host smoke suite). They are mobile
		// concepts: a Mac switches capture and playback by *device selection*
		// (enumerateDevices:/setDevice:), not by an earpiece/speaker toggle or a front/back camera
		// flip. The cross-platform façade treats SwitchCamera/SetSpeakerphone as no-ops on macOS.

		// - (int)renewToken: — the other half of the TokenPrivilegeWillExpire callback below.
		[Export ("renewToken:")]
		nint RenewToken (string token);

		// - (int)enableAudioVolumeIndication:smooth:reportVad: — interval in ms; smooth is the
		// smoothing factor (the header recommends 3). The header claims interval <= 0 disables,
		// but the 4.6.2 engine answers -2 (invalid argument) to 0 — don't rely on it.
		[Export ("enableAudioVolumeIndication:smooth:reportVad:")]
		nint EnableAudioVolumeIndication (nint interval, nint smooth, bool reportVad);

		// ------------------------------------------------------------------------------------
		// Extension controls
		// ------------------------------------------------------------------------------------
		// These switches all live on the engine and are therefore always callable — but each one
		// only *works* when the matching extension framework is in the app bundle, which is what
		// the Net.Agora.Extensions.*.Mac packages carry. Without it the engine answers a failure
		// code from a call that compiled and linked perfectly; see src/Agora.Extension.md.

		// - (int)setAINSMode:mode: — the AI noise suppressor (Net.Agora.Extensions.Ains.Mac).
		[Export ("setAINSMode:mode:")]
		nint SetAinsMode (bool enabled, AgoraAinsMode mode);

		// - (int)setVoiceBeautifierPreset: and - (int)setAudioEffectPreset: — the voice changers
		// and room reverbs (Net.Agora.Extensions.AudioBeauty.Mac). The two overwrite each other;
		// AgoraRtcEngineKit.h spells out the interplay.
		[Export ("setVoiceBeautifierPreset:")]
		nint SetVoiceBeautifierPreset (AgoraVoiceBeautifierPreset preset);

		[Export ("setAudioEffectPreset:")]
		nint SetAudioEffectPreset (AgoraAudioEffectPreset preset);

		// - (int)enableVirtualBackground:backData:segData: — background blur or replacement
		// (Net.Agora.Extensions.VirtualBackground.Mac). segData is optional; passing null takes
		// the engine's own segmentation defaults.
		[Export ("enableVirtualBackground:backData:segData:")]
		nint EnableVirtualBackground (bool enable, [NullAllowed] AgoraVirtualBackgroundSource backData, [NullAllowed] AgoraSegmentationProperty segData);

		// The image-quality filters (Net.Agora.Extensions.ClearVision.Mac). Each takes its own
		// options object; passing null takes the engine's defaults. AgoraRtcEngineKit.h notes that
		// low-light enhancement wants the denoiser enabled first.
		[Export ("setVideoDenoiserOptions:options:")]
		nint SetVideoDenoiserOptions (bool enable, [NullAllowed] AgoraVideoDenoiserOptions options);

		[Export ("setLowlightEnhanceOptions:options:")]
		nint SetLowlightEnhanceOptions (bool enable, [NullAllowed] AgoraLowlightEnhanceOptions options);

		[Export ("setColorEnhanceOptions:options:")]
		nint SetColorEnhanceOptions (bool enable, [NullAllowed] AgoraColorEnhanceOptions options);

		// - (int)enableFaceDetection: — local face detection
		// (Net.Agora.Extensions.FaceDetection.Mac).
		[Export ("enableFaceDetection:")]
		nint EnableFaceDetection (bool enable);
	}

	// AgoraVirtualBackgroundSource — AgoraObjects.h. What to put behind the segmented person: a
	// solid Color, an Img (a file path in Source), a Blur of the real background, or a Video.
	[BaseType (typeof (NSObject))]
	public interface AgoraVirtualBackgroundSource {
		[Export ("backgroundSourceType", ArgumentSemantic.Assign)]
		AgoraVirtualBackgroundSourceType BackgroundSourceType { get; set; }

		// 0xRRGGBB, used when BackgroundSourceType is Color.
		[Export ("color")]
		nuint Color { get; set; }

		// A local file path, used when BackgroundSourceType is Img or Video.
		[NullAllowed]
		[Export ("source", ArgumentSemantic.Copy)]
		string Source { get; set; }

		[Export ("blurDegree", ArgumentSemantic.Assign)]
		AgoraBlurDegree BlurDegree { get; set; }
	}

	// AgoraSegmentationProperty — AgoraObjects.h. The segmentation model and its greenscreen
	// threshold. Bound as an opaque type: the defaults are what every caller here uses, and it
	// exists in this binding only so EnableVirtualBackground can take its documented nil.
	[BaseType (typeof (NSObject))]
	public interface AgoraSegmentationProperty {
	}

	// AgoraVideoDenoiserOptions — AgoraObjects.h.
	[BaseType (typeof (NSObject))]
	public interface AgoraVideoDenoiserOptions {
		[Export ("mode", ArgumentSemantic.Assign)]
		AgoraVideoDenoiserMode Mode { get; set; }

		[Export ("level", ArgumentSemantic.Assign)]
		AgoraVideoDenoiserLevel Level { get; set; }
	}

	// AgoraLowlightEnhanceOptions — AgoraObjects.h.
	[BaseType (typeof (NSObject))]
	public interface AgoraLowlightEnhanceOptions {
		[Export ("mode", ArgumentSemantic.Assign)]
		AgoraLowlightEnhanceMode Mode { get; set; }

		[Export ("level", ArgumentSemantic.Assign)]
		AgoraLowlightEnhanceLevel Level { get; set; }
	}

	// AgoraColorEnhanceOptions — AgoraObjects.h. Both are 0..1 floats; skinProtectLevel holds back
	// the enhancement on skin tones, which over-saturate first.
	[BaseType (typeof (NSObject))]
	public interface AgoraColorEnhanceOptions {
		[Export ("strengthLevel")]
		float StrengthLevel { get; set; }

		[Export ("skinProtectLevel")]
		float SkinProtectLevel { get; set; }
	}

	// AgoraRtcEngineDelegate — AgoraRtcEngineDelegate.h. Every method there is @optional; scoped
	// here to the callbacks the thin wrapper turns into C# events.
	[Protocol]
	[Model]
	[BaseType (typeof (NSObject))]
	public interface AgoraRtcEngineDelegate {

		// The [EventArgs] names below become public <name>EventArgs classes (the generator
		// appends the suffix) feeding the events on AgoraRtcEngineKit — part of the package's
		// API surface, so renaming one is a breaking change. The names deliberately match
		// Net.Agora.Video.iOS's for every callback both bindings carry, so cross-platform code
		// sees identically-named EventArgs types on either package.

		[Export ("rtcEngine:didJoinChannel:withUid:elapsed:")]
		[EventArgs ("AgoraRtcDidJoinChannel")]
		void DidJoinChannel (AgoraRtcEngineKit engine, string channel, nuint uid, nint elapsed);

		[Export ("rtcEngine:didLeaveChannelWithStats:")]
		[EventArgs ("AgoraRtcDidLeaveChannel")]
		void DidLeaveChannel (AgoraRtcEngineKit engine, AgoraChannelStats stats);

		[Export ("rtcEngine:didJoinedOfUid:elapsed:")]
		[EventArgs ("AgoraRtcRemoteUserJoined")]
		void DidJoinedOfUid (AgoraRtcEngineKit engine, nuint uid, nint elapsed);

		[Export ("rtcEngine:didOfflineOfUid:reason:")]
		[EventArgs ("AgoraRtcRemoteUserOffline")]
		void DidOfflineOfUid (AgoraRtcEngineKit engine, nuint uid, AgoraUserOfflineReason reason);

		[Export ("rtcEngine:didOccurError:")]
		[EventArgs ("AgoraRtcErrorOccurred")]
		void DidOccurError (AgoraRtcEngineKit engine, AgoraErrorCode errorCode);

		// A remote user muting/unmuting their microphone or camera — the "who is muted" signals a
		// call UI shows.
		[Export ("rtcEngine:didAudioMuted:byUid:")]
		[EventArgs ("AgoraRtcRemoteAudioMuted")]
		void DidAudioMuted (AgoraRtcEngineKit engine, bool muted, nuint uid);

		[Export ("rtcEngine:didVideoMuted:byUid:")]
		[EventArgs ("AgoraRtcRemoteVideoMuted")]
		void DidVideoMuted (AgoraRtcEngineKit engine, bool muted, nuint uid);

		// Speaker volumes, at the cadence EnableAudioVolumeIndication configured. The speakers
		// array carries the loudest few; uid 0 means the local user in the local callback.
		[Export ("rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:")]
		[EventArgs ("AgoraRtcAudioVolumeIndicated")]
		void ReportAudioVolumeIndication (AgoraRtcEngineKit engine, AgoraRtcAudioVolumeInfo[] speakers, nint totalVolume);

		// - (void)rtcEngine:tokenPrivilegeWillExpire: — fire RenewToken from here.
		[Export ("rtcEngine:tokenPrivilegeWillExpire:")]
		[EventArgs ("AgoraRtcTokenPrivilegeWillExpire")]
		void TokenPrivilegeWillExpire (AgoraRtcEngineKit engine, string token);

		// The connection lifecycle (connecting/connected/reconnecting/...). The reason parameter
		// is AgoraConnectionChangedReason — ~30 values; carried as its raw NSInteger rather than
		// binding an enum consumers would mostly pass through as a number anyway.
		[Export ("rtcEngine:connectionChangedToState:reason:")]
		[EventArgs ("AgoraRtcConnectionChanged")]
		void ConnectionChangedToState (AgoraRtcEngineKit engine, AgoraConnectionState state, nint reason);
	}
}
