using System;
using ObjCRuntime;
using Foundation;

namespace Net.Agora.Voice.Mac {

	// Hand-written against the real AgoraRtcKit.xcframework headers from AgoraRtcEngine_macOS 4.6.2
	// (the audio-only surface of the macOS RTC engine) rather than generated by Objective Sharpie —
	// same reasoning as Net.Agora.Video.Mac's ApiDefinition.cs: sharpie's bundled clang cannot
	// parse SDKs from current Xcode. On macOS there is no separate voice build: this binds the same AgoraRtcKit framework and
	// headers as the video package, exposing only the audio surface — see the .csproj on why the payload is the same size.
	//
	// Scoped to what the thin Net.Agora.Voice client needs — create the engine, join/leave a
	// channel, publish/mute audio, drive the audio route, report speaker volumes, and the delegate
	// callbacks for those — not the SDK's full surface. The video entry points the shared engine
	// also exposes are deliberately not bound: this package is the audio-only face of the RTC
	// engine, and an app that wants video uses Net.Agora.Video.Mac instead (the two are mutually
	// exclusive — same AgoraRtcKit framework name). A consumer that needs a video call should not be
	// reaching for the Voice package at all.
	// Extend here as more of AgoraRtcEngineKit.h is needed. Enums live in StructsAndEnums.cs; the
	// block delegate types stay here — the binding generator emits a trampoline for a delegate
	// declared in the api definition file itself, and duplicates it if the same type is declared
	// again in the core source file.

	// Objective-C blocks used as completion handlers on AgoraRtcEngineKit (AgoraRtcEngineKit.h).
	public delegate void AgoraJoinChannelSuccessHandler (string channel, nuint uid, nint elapsed);
	public delegate void AgoraLeaveChannelHandler (AgoraChannelStats stats);

	// AgoraChannelStats — AgoraObjects.h. Bound as an opaque type: it is only used here as the
	// LeaveChannel completion handler's parameter type. Add properties as callers need the stats.
	[BaseType (typeof (NSObject))]
	public interface AgoraChannelStats {
	}

	// AgoraRtcEngineConfig — AgoraObjects.h. Only the two properties every engine needs.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtcEngineConfig {
		[Export ("appId", ArgumentSemantic.Copy)]
		[NullAllowed]
		string AppId { get; set; }

		[Export ("channelProfile")]
		AgoraChannelProfile ChannelProfile { get; set; }
	}

	// AgoraRtcAudioVolumeInfo — AgoraObjects.h. One speaker's entry in the volume indication
	// callback: uid 0 is the local user in the local callback, volume ranges 0–255.
	[BaseType (typeof (NSObject))]
	public interface AgoraRtcAudioVolumeInfo {
		[Export ("uid")]
		nuint Uid { get; set; }

		[Export ("volume")]
		nuint Volume { get; set; }
	}

	[BaseType (typeof (NSObject))]
	public interface AgoraRtcEngineKit {

		// + (instancetype)sharedEngineWithConfig:delegate:
		[Static]
		[Export ("sharedEngineWithConfig:delegate:")]
		AgoraRtcEngineKit SharedEngine (AgoraRtcEngineConfig config, [NullAllowed] AgoraRtcEngineDelegate del);

		// + (void)destroy — call after releasing every reference to the shared instance.
		[Static]
		[Export ("destroy")]
		void Destroy ();

		// - (int)joinChannelByToken:channelId:info:uid:joinSuccess:
		[Export ("joinChannelByToken:channelId:info:uid:joinSuccess:")]
		nint JoinChannel ([NullAllowed] string token, string channelId, [NullAllowed] string info, nuint uid, [NullAllowed] AgoraJoinChannelSuccessHandler joinSuccess);

		// - (int)leaveChannel:(void(^)(AgoraChannelStats*))
		[Export ("leaveChannel:")]
		nint LeaveChannel ([NullAllowed] AgoraLeaveChannelHandler leaveChannelBlock);

		[Export ("setChannelProfile:")]
		nint SetChannelProfile (AgoraChannelProfile profile);

		[Export ("setClientRole:")]
		nint SetClientRole (AgoraClientRole role);

		[Export ("enableAudio")]
		nint EnableAudio ();

		[Export ("disableAudio")]
		nint DisableAudio ();

		[Export ("muteLocalAudioStream:")]
		nint MuteLocalAudioStream (bool mute);

		// - (int)renewToken: — the other half of the DidRequestToken/TokenPrivilegeWillExpire
		// callbacks below.
		[Export ("renewToken:")]
		nint RenewToken (string token);

		// Deliberately NOT bound on macOS: -setEnableSpeakerphone: and
		// -setDefaultAudioRouteToSpeakerphone:. The shared AgoraRtcEngineKit.h declares both, but
		// they are iOS-only — the macOS engine raises "unrecognized selector" for them (verified on
		// the host smoke suite). Speakerphone routing is a mobile concept; a Mac selects its audio
		// output by *device* (enumerateDevices:/setDevice:), not an earpiece/speaker toggle. The
		// cross-platform façade treats SetSpeakerphone as a no-op on macOS.

		// - (int)enableAudioVolumeIndication:smooth:reportVad: — interval in ms; smooth is the
		// smoothing factor (the header recommends 3). The header claims interval <= 0 disables,
		// but the 4.6.2 engine answers -2 (invalid argument) to 0 — don't rely on it.
		[Export ("enableAudioVolumeIndication:smooth:reportVad:")]
		nint EnableAudioVolumeIndication (nint interval, nint smooth, bool reportVad);

		// ------------------------------------------------------------------------------------
		// Extension controls
		// ------------------------------------------------------------------------------------
		// These switches all live on the engine and are therefore always callable — but each one
		// only *works* when the matching extension framework is in the app bundle, which is what
		// the Net.Agora.Extensions.*.iOS packages carry. Without it the engine answers a failure
		// code from a call that compiled and linked perfectly; see src/Agora.Extension.md.

		// - (int)setAINSMode:mode: — the AI noise suppressor
		// (Net.Agora.Extensions.Ains.iOS).
		[Export ("setAINSMode:mode:")]
		nint SetAinsMode (bool enabled, AgoraAinsMode mode);

		// - (int)setVoiceBeautifierPreset: and - (int)setAudioEffectPreset: — the voice changers
		// and room reverbs (Net.Agora.Extensions.AudioBeauty.iOS). The two overwrite each other;
		// AgoraRtcEngineKit.h spells out the interplay.
		[Export ("setVoiceBeautifierPreset:")]
		nint SetVoiceBeautifierPreset (AgoraVoiceBeautifierPreset preset);

		[Export ("setAudioEffectPreset:")]
		nint SetAudioEffectPreset (AgoraAudioEffectPreset preset);

		// The video-only filters (virtual background, the ClearVision image-quality options, face
		// detection) are deliberately absent here: this is the voice build of AgoraRtcKit, which
		// has no video pipeline for them to act on. They are bound in Net.Agora.Video.iOS.
	}

	// AgoraRtcEngineDelegate — AgoraRtcEngineDelegate.h. Every method there is @optional; scoped
	// here to the callbacks the thin wrapper turns into C# events.
	[Protocol]
	[Model]
	[BaseType (typeof (NSObject))]
	public interface AgoraRtcEngineDelegate {

		[Export ("rtcEngine:didJoinChannel:withUid:elapsed:")]
		void DidJoinChannel (AgoraRtcEngineKit engine, string channel, nuint uid, nint elapsed);

		[Export ("rtcEngine:didLeaveChannelWithStats:")]
		void DidLeaveChannel (AgoraRtcEngineKit engine, AgoraChannelStats stats);

		[Export ("rtcEngine:didJoinedOfUid:elapsed:")]
		void DidJoinedOfUid (AgoraRtcEngineKit engine, nuint uid, nint elapsed);

		[Export ("rtcEngine:didOfflineOfUid:reason:")]
		void DidOfflineOfUid (AgoraRtcEngineKit engine, nuint uid, AgoraUserOfflineReason reason);

		[Export ("rtcEngine:didOccurError:")]
		void DidOccurError (AgoraRtcEngineKit engine, AgoraErrorCode errorCode);

		// A remote user muting/unmuting their audio — the voice UI's "who is muted" signal.
		[Export ("rtcEngine:didAudioMuted:byUid:")]
		void DidAudioMuted (AgoraRtcEngineKit engine, bool muted, nuint uid);

		// Speaker volumes, at the cadence EnableAudioVolumeIndication configured. The speakers
		// array carries the loudest few; uid 0 means the local user in the local callback.
		[Export ("rtcEngine:reportAudioVolumeIndicationOfSpeakers:totalVolume:")]
		void ReportAudioVolumeIndication (AgoraRtcEngineKit engine, AgoraRtcAudioVolumeInfo[] speakers, nint totalVolume);

		// - (void)rtcEngine:tokenPrivilegeWillExpire: — fire RenewToken from here.
		[Export ("rtcEngine:tokenPrivilegeWillExpire:")]
		void TokenPrivilegeWillExpire (AgoraRtcEngineKit engine, string token);

		// The connection lifecycle (connecting/connected/reconnecting/...). The reason parameter
		// is AgoraConnectionChangedReason — ~30 values; carried as its raw NSInteger rather than
		// binding an enum consumers would mostly pass through as a number anyway.
		[Export ("rtcEngine:connectionChangedToState:reason:")]
		void ConnectionChangedToState (AgoraRtcEngineKit engine, AgoraConnectionState state, nint reason);
	}
}
